development:
  sendgrid_username: test
  sendgrid_password: test
  pre_notification_time: '24'
production:  
  sendgrid_username : ENV['sendgrid_username']
  sendgrid_username : ENV['sendgrid_password']
  pre_notification_time: '24'